receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
  resource:
    attributes:
      - action: insert
        key: loki.resource.labels
        value: deployment.environment, service.namespace
  
exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: 0.0.0.0:8889
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    default_labels_enabled:
      exporter: true
      job: true
      instance: true
      level: true
  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"
    # headers:
    #   Authorization: "Basic ${PROM_AUTH}"
    resource_to_telemetry_conversion:
      enabled: true # Convert resource attributes to metric labels. Need only for environment resource.
  otlp/traces:
    endpoint: "tempo:4317"
    tls:
      insecure: true

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]
  telemetry:
    logs:
      level: "debug"
      encoding: "json"
      initial_fields: 
        service: "opentelemetry collector"
    metrics:
      level: basic
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8888

  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/traces]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite]
    logs:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [loki]
